### ISSUE TITLE
Install stable?

### ISSUE THREAD

**Issue by adzenith** [metacollin/homebrew-kicad#10]
The README's been changed to say that there's a stable version, but I still only see the unstable version. There's no version number in the formula and no artifact to download. I don't see any other branches. Am I doing something wrong?
Thanks! I really appreciate having Kicad in Homebrew :+1:

**Comment by adzenith** [comment]
Looks like it's also missing the `--without-default-paths` argument. Oddly, `brew install` doesn't complain if you pass it arguments that don't exist.

**Comment by metacollin** [comment]
@adzenith, embarassingly, my repository accidentally had an ancient file pushed to this repo.  I have no idea how I managed to do that, but the kicad.rb file was essentially nonsense and not meant to contain what it did.  I've corrected this, please try it now.

Also, I am in the process of hopefully getting this accepted to the official homebrew-science repo soon.  But for now, this tap works well.  Its what I use to track the development builds of kicad.  Let me know if you run into any problems.  The file is now the correct one and reflects the documentation :).

**Comment by adzenith** [comment]
Thanks so much! I hope it gets included in homebrew-science. :microscope:

**Comment by metacollin** [comment]
Thanks! Sorry it took me 10 days to respond, I've not had as much time as I'd like to work on this stuff lately, but things are finally letting up a bit.  And if you have any more problems, definitely open a new issue - I should respond a little quicker this time.

**Comment by adzenith** [comment]
No worries! Thanks for making the formula :beer:
