### ISSUE TITLE
Caveats are swapped

### ISSUE THREAD

**Issue by adzenith** [metacollin/homebrew-kicad#12]
I believe that the [caveats](https://github.com/metacollin/homebrew-kicad/blob/master/kicad.rb#L177) are swapped—that is, if I build without default paths it should tell me that component libraries are set up for me, and if I build with default paths then I would need to clone the git repository.
Thanks!

**Comment by metacollin** [comment]
D'oh! Right you are.  Fixed.

**Comment by adzenith** [comment]
Thanks!
