### ISSUE TITLE
'boost/context/fcontext.hpp' file not found

### ISSUE THREAD

**Issue by ohhorob** [metacollin/homebrew-kicad#14]
Tried to install from homebrew `brew install kicad --with-brewed-library --with-wx31 --without-menu-icons`

Failed with this error. Full log directory attached.

cd /tmp/kicad-20160831-76285-18afv2a/kicad-4.0.3/build/pcbnew/router && /usr/local/Library/Homebrew/shims/super/clang++   -DHAVE_STDINT_H -DKICAD_KEEPCASE -DPCBNEW -DUSE_WX_GRAPHICS_CONTEXT -DUSE_WX_OVERLAY -DWXUSINGDLL -DWX_COMPATIBILITY -D_F
ILE_OFFSET_BITS=64 -D__WXMAC__ -D__WXOSX_COCOA__ -D__WXOSX__ -I/tmp/kicad-20160831-76285-18afv2a/kicad-4.0.3/include -I/tmp/kicad-20160831-76285-18afv2a/kicad-4.0.3/pcbnew/router/. -I/private/tmp/kicad-20160831-76285-18afv2a/kicad-4.0.3/wxk/li
b/wx/include/osx_cocoa-unicode-3.1 -I/private/tmp/kicad-20160831-76285-18afv2a/kicad-4.0.3/wxk/include/wx-3.1 -I/tmp/kicad-20160831-76285-18afv2a/kicad-4.0.3/pcbnew/router/.. -I/tmp/kicad-20160831-76285-18afv2a/kicad-4.0.3/pcbnew/router/../../
include -I/tmp/kicad-20160831-76285-18afv2a/kicad-4.0.3/pcbnew/router/../../pcbnew -I/tmp/kicad-20160831-76285-18afv2a/kicad-4.0.3/pcbnew/router/../../polygon -I/usr/local/include -I/tmp/kicad-20160831-76285-18afv2a/kicad-4.0.3/build  -Wall  -
fPIC -Wno-strict-aliasing -D__ASSERTMACROS__ -I/private/tmp/kicad-20160831-76285-18afv2a/kicad-4.0.3/wxk/include/wx-3.1 -O2 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk 
-mmacosx-version-min=10.11   -o CMakeFiles/pnsrouter.dir/pns_utils.cpp.o -c /tmp/kicad-20160831-76285-18afv2a/kicad-4.0.3/pcbnew/router/pns_utils.cpp
In file included from /tmp/kicad-20160831-76285-18afv2a/kicad-4.0.3/common/tool/tool_manager.cpp:46:
/tmp/kicad-20160831-76285-18afv2a/kicad-4.0.3/include/tool/coroutine.h:30:10: fatal error: 'boost/context/fcontext.hpp' file not found
# include <boost/context/fcontext.hpp>

```
     ^
```

[kicad.zip](https://github.com/metacollin/homebrew-kicad/files/448777/kicad.zip)

Is there anything else I need to provide to report the issue?

**Comment by ohhorob** [comment]
Possibly related? -- https://github.com/PowerDNS/pdns/issues/4014#issuecomment-228724900

> It looks like, apart from the change in filepath, the namespace also changed from boost::context::make_fcontext to boost::context::detail::make_fcontext

**Comment by ddavidebor** [comment]
I get this error too, with --HEAD now
