### ISSUE TITLE
make: *** [all] Error 2 (--HEAD --with-nice-curves --with-oce)

### ISSUE THREAD

**Issue by ohhorob** [metacollin/homebrew-kicad#17]
On macOS Sierra 10.12.4 (16E194)

$ xcode-select -p
/Library/Developer/CommandLineTools

$ brew install kicad --HEAD --with-nice-curves --with-oce
==> Installing kicad from metacollin/kicad
==> Cloning https://git.launchpad.net/kicad
Updating ~/Library/Caches/Homebrew/kicad--git
==> Checking out branch master
==> cmake ../ -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kicad/HEAD-ac9a64a -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12 -DKICAD_REPO_NAME=brewed_product -DKICAD_SKIP_BOOST=ON -DwxWidgets_CONF
==> make -j8
Last 15 lines from ~

/Library/Logs/Homebrew/kicad/02.make:
[ 37%] Building CXX object bitmaps_png/CMakeFiles/bitmaps.dir/cpp_48/icon_modedit.cpp.o
[ 37%] Building CXX object bitmaps_png/CMakeFiles/bitmaps.dir/cpp_48/icon_pcbnew.cpp.o
[ 37%] Building CXX object bitmaps_png/CMakeFiles/bitmaps.dir/cpp_48/icon_bitmap2component.cpp.o
[ 37%] Building CXX object bitmaps_png/CMakeFiles/bitmaps.dir/cpp_48/icon_pcbcalculator.cpp.o
[ 37%] Building CXX object bitmaps_png/CMakeFiles/bitmaps.dir/cpp_48/viewlibs_icon.cpp.o
[ 37%] Building CXX object bitmaps_png/CMakeFiles/bitmaps.dir/cpp_48/icon_pagelayout_editor.cpp.o
[ 37%] Building CXX object bitmaps_png/CMakeFiles/bitmaps.dir/cpp_48/wizard_add_fplib_icon.cpp.o
[ 37%] Building CXX object bitmaps_png/CMakeFiles/bitmaps.dir/cpp_other/tune_diff_pair_length_legend.cpp.o
[ 38%] Building CXX object bitmaps_png/CMakeFiles/bitmaps.dir/cpp_other/tune_diff_pair_skew_legend.cpp.o
[ 38%] Building CXX object bitmaps_png/CMakeFiles/bitmaps.dir/cpp_other/tune_single_track_length_legend.cpp.o
[ 38%] Linking CXX static library libbitmaps.a
[ 38%] Built target bitmaps
[ 38%] Linking CXX static library libgal.a
[ 38%] Built target gal
make: *** [all] Error 2

[02.make.txt](https://github.com/metacollin/homebrew-kicad/files/1048480/02.make.txt)

**Comment by metacollin** [comment]
Hi, as far as I know, KiCad requires Xcode be installed.  I've added the appropriate flags to the formulae.  Thanks!
