### ISSUE TITLE
Failing to install

### ISSUE THREAD

**Issue by bjpirt** [metacollin/homebrew-kicad#3]
KiCad was failing to install for me:

```
$ brew install kicad --HEAD
==> Installing kicad from metacollin/homebrew-kicad
Error: undefined method `[]' for :universal:Symbol
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/options.rb:61:in `create'
/usr/local/Library/Homebrew/options.rb:61:in `map'
/usr/local/Library/Homebrew/options.rb:61:in `create'
/usr/local/Library/Homebrew/dependable.rb:27:in `options'
/usr/local/Library/Homebrew/dependency.rb:33:in `to_formula'
/usr/local/Library/Homebrew/dependency.rb:88:in `expand'
/usr/local/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Library/Homebrew/dependency.rb:76:in `expand'
/usr/local/Library/Homebrew/dependency.rb:88:in `expand'
/usr/local/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Library/Homebrew/dependency.rb:76:in `expand'
/usr/local/Library/Homebrew/formula.rb:574:in `recursive_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:96:in `verify_deps_exist'
/usr/local/Library/Homebrew/formula_installer.rb:89:in `prelude'
/usr/local/Library/Homebrew/cmd/install.rb:161:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:84:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:84:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:84:in `install'
/usr/local/Library/brew.rb:135:in `send'
```

I'm running 10.8.5 - any suggestions?

**Comment by metacollin** [comment]
Yes - run brew update.  I experienced this issue on my own 10.8 virtual machine and fixed it in a commit late last night.  In fact, due to some clumsiness on my part, there were damage control commits up until an hour or two ago, so anyone who sees this should run brew update.  

Sorry about that, entirely my fault.

**Comment by bjpirt** [comment]
That made the build get a lot further, but now it's failing at trying to build wxpython:

```
==> Installing kicad dependency: wxkicad
==> Downloading https://downloads.sourceforge.net/project/wxpython/wxPython/3.0.2.0/wxPython-src-3.0.2.0.tar.bz2
######################################################################## 100.0%
==> Downloading https://gist.githubusercontent.com/metacollin/2d5760743df73c939d53/raw/37c8f5f823c60f76ae30d6acf54ca03f1b11f4f9/wxp.patch
######################################################################## 100.0%
==> Patching
patching file Makefile.in
patching file configure
patching file configure.in
patching file include/wx/osx/cocoa/private/overlay.h
patching file include/wx/overlay.h
patching file include/wx/private/overlay.h
patching file src/common/translation.cpp
patching file src/osx/cocoa/overlay.mm
patching file src/osx/webview_webkit.mm
==> ./configure --prefix=/usr/local/Cellar/wxkicad/3.0.2.0 --with-opengl --enable-aui --enable-utf8 --enable-html --enable-stl --with-libjpeg=builtin --with-libpng=builtin --with-regex=builtin --with-libtiff=builtin --with-zlib=builtin --
==> make -j6 install
==> 
==> *****
==> The custom KiCad version of wx has built successfully. Woohoo!
==> *****
==> But we're not done yet.  Hold onto your butts, now building wxpython.
==> /usr/bin/python setup.py build_ext WXPORT=osx_cocoa WX_CONFIG=/usr/local/Cellar/wxkicad/3.0.2.0/bin/wx-config UNICODE=1 BUILD_BASE=/private/tmp/wxkicad-8mUZl8/wxPython-src-3.0.2.0
creating /private/tmp/wxkicad-8mUZl8/wxPython-src-3.0.2.0/temp.macosx-10.8-x86_64-2.7/src/osx_cocoa
clang -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -Wunused-command-line-argument-hard-error-in-future -Wunused-command-line-argument-hard-error-in-future -pipe -DSWIG_TYPE_TABLE=_wxPython_table -DSWIG_PYTHON_OUTPUT_TUPLE -DSWIG_PYTHON_SILENT_MEMLEAK -DWXP_USE_THREAD=1 -UNDEBUG -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__ -Iinclude -Isrc -I/usr/local/Cellar/wxkicad/3.0.2.0/lib/wx/include/osx_cocoa-unicode-3.0 -I/usr/local/Cellar/wxkicad/3.0.2.0/include/wx-3.0 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/helpers.cpp -o /private/tmp/wxkicad-8mUZl8/wxPython-src-3.0.2.0/temp.macosx-10.8-x86_64-2.7/src/helpers.o -O3
clang: error: unknown argument: '-mno-fused-madd' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
error: command 'clang' failed with exit status 1
```

**Comment by bjpirt** [comment]
Adding in:

```
ENV['ARCHFLAGS'] = "-Wno-error=unused-command-line-argument-hard-error-in-future"
```

to line 57 of wxkicad.rb got me through that stage. Now it's failing at the kicad stage:

```
==> Installing kicad
==> Cloning https://code.launchpad.net/~kicad-product-committers/kicad/product
Not checking SSL certificate for code.launchpad.net.
==> Downloading https://gist.githubusercontent.com/metacollin/97b547034d144f483c0f/raw/8d7f4fc2b119b126bb76322e5c1461f61bf37ef7/boost.patch                                                                                                  
######################################################################## 100.0%
==> Patching
patching file CMakeModules/download_boost.cmake
==> cmake ../ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kicad/HEAD -DCMAKE_OSX_DEPLOYMENT_TARGET=10.8 -DwxWidgets_CONFIG_EXECUTABLE=/usr/local/Cellar/wxkicad/3.0.2.0/b
==> make -j6
Please, set your name with the 'whoami' command.
E.g. bzr whoami "Your Name <name@example.com>"
make[2]: *** [../.downloads-by-cmake/boost_1_57_0/src/boost-stamp/boost-bzr_commit_boost] Error 3
make[1]: *** [CMakeFiles/boost.dir/all] Error 2
make: *** [all] Error 2
```

I've tried running bzr whoami and it's building again - we'll see if that sorted it, but I wonder if it's possible for others to make this step require less human intervention.

**Comment by metacollin** [comment]
Hi, hold off on trying to rebuild just a few minutes.  Thanks for your patience.  Kicad will build, then fail at the very end to install, which is the worst outcome. I am waiting for a build to finish, but I think I fixed the problem, but wait until there is one more commit than there is now to attempt rebuilding, it will fail right now.  Sorry :(.

Anyway, thanks for finding this, I had no idea bzr would through an error that would kill cmake if the user doesn't have bzr totally setup.  That's a pretty irritating "feature" to be honest.  I am just going to switch back to using the github mirror and nip that one in the bud, the only reason for using bzr was because homebrew prefers not to use source mirrors when possible, but there is no advantage to using bzr that is worth this problem.

**Comment by metacollin** [comment]
I know this is probably very frustrating, I don't mean to waste people's time.  On the plus, wxkicad is fine, so if that built, there is no fixes left on that front and you won't need to build that formula again.  Progress!

Sorry again.  I'll reply again once I have confirmed kicad actually builds, which should be in a few minutes hopefully.

**Comment by bjpirt** [comment]
I'd already left it building and it failed with this message:

```
==> Installing kicad from metacollin/homebrew-kicad
==> Cloning https://code.launchpad.net/~kicad-product-committers/kicad/product
Updating /Library/Caches/Homebrew/kicad--bzr
==> Downloading https://gist.githubusercontent.com/metacollin/97b547034d144f483c0f/raw/8d7f4fc2b119b126bb76322e5c1461f61bf37ef7/boost.patch
Already downloaded: /Library/Caches/Homebrew/kicad--patch-e3a5b58219123e69a569f4b68fa5ee1acf356b00.patch
==> Patching
patching file CMakeModules/download_boost.cmake
==> cmake ../ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kicad/HEAD -DCMAKE_OSX_DEPLOYMENT_TARGET=10.8 -DwxWidgets_CONFIG_EXECUTABLE=/usr/local/Cellar/wxkicad/3.0.2.0/b
==> make -j6
...updated 11503 targets...
[ 32%] No install step for 'boost'
[ 32%] Completed 'boost'
[ 32%] Built target boost
make: *** [all] Error 2
```

Getting there :-)

**Comment by metacollin** [comment]
I can't thank you enough, having bzr fully setup, I was also blind to any of these problems.  All the problems making the build fail are, believe it or not, all the same issue with bzr not being configured as thoroughly as it likes.  It also ignores any environment variables that are supposed to get around this limitation.  

Anyway, I am linking to an updated patch on gist in the formula that should make bzr behave once and for all.  These errors let me know exactly where to find the problem, a pleasant but too uncommon event :).  Nearly done, will reply after commit.

**Comment by metacollin** [comment]
Wow, just to complicate matters, sourceforge (where boost is downloaded from) went down, had some issues, and now the boost tar.gz has a different md5sum..... thanks, great timing.

Unless I'm undergoing one serious man-in-the-middle attack on my residential internet connection.  But I think sourceforge just sucks =P.

**Comment by bjpirt** [comment]
I had sourceforge issues yesterday - it was down and then started serving out the wrong cert as well as getting into an endless redirect.

I think your assessment is correct ;-)

**Comment by metacollin** [comment]
Sigh, sourceforge had impeccably poor timing (as usual).  I moved things around a bit to allow for bouts of sourceforge going into pants crapping mode and breaking things  =P.

I fully tested this one and the app it built this time.  I am pretty confident if you brew update and, once more, try to build kicad, it will work.  It also still requires bzr, but I made it irrelevant as to if the user had configured their bzr identity at all, or if it was totally empty (the state most users likely are in).

**Comment by bjpirt** [comment]
I brew updated but unfortunately I still get the same message about boost:

```
==> Installing kicad from metacollin/homebrew-kicad
==> Cloning https://github.com/KiCad/kicad-source-mirror.git
Cloning into '/Library/Caches/Homebrew/kicad--git'...
remote: Counting objects: 3343, done.
remote: Compressing objects: 100% (2841/2841), done.
remote: Total 3343 (delta 739), reused 2771 (delta 474), pack-reused 0
Receiving objects: 100% (3343/3343), 15.33 MiB | 853.00 KiB/s, done.
Resolving deltas: 100% (739/739), done.
Checking connectivity... done.
==> Checking out branch master
==> Downloading https://gist.githubusercontent.com/metacollin/97b547034d144f483c0f/raw/8af3be1224f100241e94d7ea3fd819d874885025/boost_new.patch
######################################################################## 100.0%
==> Patching
patching file CMakeModules/download_boost.cmake
==> Downloading http://ufpr.dl.sourceforge.net/project/boost/boost/1.57.0/boost_1_57_0.tar.bz2
######################################################################## 100.0%
==> cmake ../ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kicad/HEAD -DCMAKE_OSX_DEPLOYMENT_TARGET=10.8 -DwxWidgets_CONFIG_EXECUTABLE=/usr/local/Cellar/wxkicad/3.0.2.0/b
==> make -j6
...updated 11503 targets...
[ 32%] No install step for 'boost'
[ 32%] Completed 'boost'
[ 32%] Built target boost
make: *** [all] Error 2
```

Sorry :-(

I appreciate all the effort you've put into this - it will be great once it's going! Thanks

**Comment by metacollin** [comment]
I need to go to bed unfortunately, but it would be helpful if you could post the contents of ~/Library/Logs/Homebrew/kicad/02.make on your system in the meantime. If its too long to paste directly, a link to gist or text dump service of choice would be just as good :).  

I'll see what I can do as soon as possible, but for now I have to sleep.  Thanks for your help!

**Comment by bjpirt** [comment]
No worries - I get the need to sleep :-)

The gist is here: https://gist.github.com/bjpirt/457c00541c3190360854

**Comment by shaneburrell** [comment]
You may want to try untap , clear cache and retry.  No problems building on Yosemite as of a few minutes ago.

**Comment by bjpirt** [comment]
Is there a specific way of doing that? I'm still quite new to homebrew. BTW, this is 10.8

**Comment by shaneburrell** [comment]
Have you checked "brew doctor" yet?

**Comment by bjpirt** [comment]
Here's the output of brew doctor:

https://gist.github.com/bjpirt/e209c2a114aafc29c33f

Any tips how to "untap"?
Cheers,
Ben

**Comment by shaneburrell** [comment]
brew untap 

Looks like you have items in usr/local/ that were not created with homebrew.  Try untapping the kicad keg and then "brew clean" and retap retry build.

**Comment by bjpirt** [comment]
Yeah, there was an install of node I think. Might just remove that manually.
Thanks for the commands - should have looked in the full man page, couldn't see them in the -h output.
Rebuilding now.
Cheers,
Ben

**Comment by bjpirt** [comment]
I untapped, cleared the cache then tried a rebuild and unfortunately it didn't fix anything - same message as before :-(

**Comment by metacollin** [comment]
So I realized what was wrong right before I was about to fall asleep.  I forgot to explicitly set the compiler to clang for wxpython.  I only do it for wxwidgets.  On 10.7 and 10.8, wxPython finds and uses g++, causing superenv to remove any libc++ flags for that part.  On 10.9 and 10.10, g++ does not exist so it uses clang, and no problems occur.

On 10.7 and 10.8, kicad, boost, and wx are all using clang and libc++.  wxPython is going to wind up using stdc++.  search for type_traits in bjpirt's gist, and there it is: its trying to include an stdc++ header, but of course kicad has no clue what that jibba jabba is, its only going to find libc++ headers.  

I am not sure how you set the compiler, build_ext has no option.  Is it as simple as CC= and CXX=? 

Here is a quick commit, but now I am actually going to bed.

**Comment by bjpirt** [comment]
I tried clearing all caches and building this again, but the same message about boost came up as the build failed. Not sure what else to try here. I might just install it in a Linux VM :-(
