### ISSUE TITLE
Looks like new patch to WX.

### ISSUE THREAD

**Issue by shaneburrell** [metacollin/homebrew-kicad#7]
Builds current fail.
[ 35%] Building CXX object common/CMakeFiles/gal.dir/gal/opengl/vertex_item.cpp.o
/tmp/kicad20150520-18580-15rtsd8/common/gal/opengl/opengl_gal.cpp:74:5: error: use of undeclared identifier 'SetViewWantsBestResolution'
    SetViewWantsBestResolution( true );
    ^

Seems to be related to new patch in KICAD BZR #5666

**Comment by metacollin** [comment]
Oh jeez, I've been experimenting with migrating KiCad to wx Phoenix, and I received this exact error and thought it was a problem related to Phoenix.  So thanks a ton for the heads up, I'll have the formula updated to apply the new patch tonight
Thanks!

**Comment by metacollin** [comment]
Fixed,
